### ISSUE TITLE
MySQL installation fails

### ISSUE THREAD

**Issue by roestzwiee** [easy-wi/installer#107]
When installing with MySQL, the installation fails as the MySQL is not starting up correctly.

Here what happened:

![image](https://user-images.githubusercontent.com/59502570/98459388-a9a86e00-219a-11eb-850b-fae5ba9514bf.png)

**Comment by tairogriz** [comment]
I just installed EasyWi today and had exactly the same problem.
This is because in MySQL 8 NO_AUTO_CREATE_USER is not available anymore. 
Delete "NO_AUTO_CREATE_USER" in the installscript in line 1210:
https://github.com/easy-wi/installer/blob/ed2a4b5b89094b8724b08cb038803564176de828/easy-wi_install.sh#L1210
If you already ran the script, you also have to delete "NO_AUTO_CREATE_USER" in /etc/mysql/conf.d/disable_strict_mode.cnf.

**Comment by roestzwiee** [comment]
Nice, thank you.

I already moved further and for the sake of learning i'm setting up my gameservers my own with docker. So i currently have no environment for testing.

**Comment by AEon-Jan** [comment]
Use MariaDB not Mysql
